name: GitHub Actions Scheduled Workflow
run-name: Health check scheduled with cron (20 min) 🚀

#on: [push]
on:
  schedule:
    # started each 5 min
    - cron: '*/20 * * * *'
    
jobs:
  check_schedule:
    runs-on: ubuntu-latest
    steps: 
      - name: Test
        run: echo "Scheduled check"
        
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python python/health.py
