name: GitHub Actions Scheduled Workflow
run-name: ${{ github.actor }} is testing out Scheduled workflows with cron in github 🚀
on:
  schedule:
    # started each 5 min
    - cron: '5 * * * *'
    
jobs:
  check_schedule:
    runs-on: ubuntu-latest
    steps: 
      - name: Test
        run: echo "Scheduled check"
